apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobs-manager-role
  namespace: default
rules:
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - get
      - list
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - create
      - delete
      - update
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jobs-manager-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: jobs-manager
  namespace: default
roleRef:
  kind: Role
  name: jobs-manager-role
  apiGroup: rbac.authorization.k8s.io

